# Generated by Django 4.2.25 on 2025-10-15 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('frecuency', models.CharField(choices=[('OCCASIONAL', 'Occasional'), ('REGULAR', 'Regular'), ('FREQUENT', 'Frequent')], default='OCCASIONAL', help_text='How often this customer makes purchases.', max_length=10, verbose_name='Purchase Frequency')),
                ('description', models.CharField(help_text='A descriptive reference for this customer.', max_length=100, verbose_name='Description')),
                ('preferences', models.TextField(blank=True, help_text="Customer's specific preferences or notes.", null=True, verbose_name='Preferences')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ['description'],
                'abstract': False,
                'indexes': [models.Index(fields=['description'], name='CLIENTS_cus_descrip_f052d7_idx'), models.Index(fields=['frecuency'], name='CLIENTS_cus_frecuen_097229_idx'), models.Index(fields=['deleted_at'], name='CLIENTS_cus_deleted_5c0e05_idx')],
            },
        ),
    ]
