# Generated by Django 5.2 on 2025-04-11 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mesasAPI', '0001_initial'),
        ('userAPI', '0002_remove_userprofile_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_inicio', models.DateTimeField()),
                ('fecha_hora_fin', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('completada', 'Completada')], default='pendiente', max_length=20)),
                ('precio_total', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='mesasAPI.mesa')),
                ('tipo_renta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='mesasAPI.tiporenta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='userAPI.userprofile')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['-fecha_hora_inicio'],
            },
        ),
    ]
