# Generated by Django 5.2 on 2025-04-11 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservasAPI', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='fecha_creacion',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='reserva',
            old_name='ultima_actualizacion',
            new_name='updated_at',
        ),
    ]
