# Generated by Django 5.0.6 on 2025-10-18 05:02

import AUTH.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCustom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('username', models.CharField(help_text='Nombre de usuario', max_length=50, unique=True, verbose_name='Nombre de usuario')),
                ('first_name', models.CharField(help_text='Nombres', max_length=50, verbose_name='Nombres')),
                ('last_name', models.CharField(help_text='Apellidos', max_length=50, verbose_name='Apellidos')),
                ('email', models.EmailField(help_text='Email', max_length=255, verbose_name='Email')),
                ('password', models.CharField(help_text='Password', max_length=255, verbose_name='Password')),
                ('phone', models.CharField(help_text='Teléfono', max_length=20, unique=True, verbose_name='Teléfono')),
                ('image_profile', models.ImageField(blank=True, help_text='Imagen de perfil', null=True, upload_to='profile_pictures/', verbose_name='Imagen de perfil')),
                ('birthday', models.DateField(blank=True, help_text='Fecha de nacimiento', null=True, verbose_name='Fecha de nacimiento')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Masculino'), ('female', 'Femenino'), ('other', 'Otro')], help_text='Genero', max_length=10, null=True, verbose_name='Genero')),
                ('role', models.CharField(choices=[('root', 'Root'), ('admin', 'Administrador'), ('client', 'Cliente')], db_index=True, default='client', help_text='Rol del usuario', max_length=50, verbose_name='Rol')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='custom_user_set', related_query_name='custom_user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='custom_user_set', related_query_name='custom_user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', AUTH.models.UserCustomManager()),
            ],
        ),
    ]
