# Generated by Django 4.2.25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AUTH', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercustom',
            name='phone',
            field=models.CharField(
                max_length=20,
                verbose_name='Teléfono',
                help_text='Teléfono',
                null=True,
                blank=True,
                unique=True,
            ),
        ),
    ]