# Generated by Django 4.2.16 on 2025-12-01 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AUTH', '0002_alter_usercustom_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercustom',
            options={'ordering': ['-created_at'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='usercustom',
            name='birthday',
            field=models.DateField(blank=True, help_text='Birthday', null=True, verbose_name='Birthday'),
        ),
        migrations.AlterField(
            model_name='usercustom',
            name='first_name',
            field=models.CharField(help_text='First Name', max_length=50, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='usercustom',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], help_text='Gender', max_length=10, null=True, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='usercustom',
            name='image_profile',
            field=models.ImageField(blank=True, help_text='Profile Picture', null=True, upload_to='profile_pictures/', verbose_name='Profile Picture'),
        ),
        migrations.AlterField(
            model_name='usercustom',
            name='last_name',
            field=models.CharField(help_text='Last Name', max_length=50, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='usercustom',
            name='phone',
            field=models.CharField(blank=True, help_text='Phone', max_length=20, null=True, unique=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='usercustom',
            name='role',
            field=models.CharField(choices=[('root', 'Root'), ('admin', 'Administrator'), ('client', 'Client')], db_index=True, default='client', help_text='User Role', max_length=50, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='usercustom',
            name='username',
            field=models.CharField(help_text='Username', max_length=50, unique=True, verbose_name='Username'),
        ),
    ]
